spring.application.name=spring-sercurity-class-3-5

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_security_jwt
spring.datasource.username=postgres
spring.datasource.password=30092007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=my-super-secret-key-for-jwt-authentication-project-2026
jwt.expiration=3600000