spring.application.name=project_class3_5

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/project_3_5_db
spring.datasource.username=postgres
spring.datasource.password=30092007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=20MB

cloudinary.cloud-name=durbdtwd4
cloudinary.api-key=741729533864646
cloudinary.api-secret=hZlNmeZ0YP1E__EkCvMgwQc0xr0
